### ISSUE TITLE
Week 3 - Experiement 3

### ISSUE THREAD

**Issue by appuCoding** [ayaskantsahu/5610-ayaskant#1]
I cant see output after clicking on spin the wheel.

**Comment by ayaskantsahu** [comment]
Could you tell me which spin wheel are we looking at here? I don't remember having any spin wheel experiment.

Would be grateful if you could mention the steps.

**Comment by appuCoding** [comment]
Sorry this is not your experiment comment . Its my mistake. I will delete this comment
