### ISSUE TITLE
Add week 6 blog in Git wiki

### ISSUE THREAD

**Issue by appuCoding** [ayaskantsahu/5610-ayaskant#12]
Add week 6 blog in Git wiki

**Comment by ayaskantsahu** [comment]
Added

**Comment by appuCoding** [comment]
I am not able to see 
![image](https://cloud.githubusercontent.com/assets/8592729/6612989/723f46f2-c85c-11e4-8452-2d3068e9ca67.png)

**Comment by ayaskantsahu** [comment]
done. the blog was available in readme.md. sorry for the confusion
