### ISSUE TITLE
Week7 - Openshift Website is down.

### ISSUE THREAD

**Issue by appuCoding** [ayaskantsahu/5610-ayaskant#13]
Your website is down , I cant review it .

![image](https://cloud.githubusercontent.com/assets/8592729/6605006/0761ea1e-c803-11e4-9f61-7e6996ff98e3.png)

**Comment by ayaskantsahu** [comment]
I checked the open shift link. It is working now. It might have been an temporary issue.

**Comment by ayaskantsahu** [comment]
Issue was resolved after couple of retries
