### ISSUE TITLE
Week7 - Suggestion

### ISSUE THREAD

**Issue by appuCoding** [ayaskantsahu/5610-ayaskant#15]
Add a method to get the records while redirected to the page itself, In current experiments until unless I add a records I am not able to see records or delete or update .

![image](https://cloud.githubusercontent.com/assets/8592729/6613036/1afff80e-c85d-11e4-82f4-b9ad7f03e448.png)

**Comment by ayaskantsahu** [comment]
Changes have been made. All data is visible on page load now.
